version '3.9'
services
    db
        container_name db
        image mysql8.0.22
        command [--default-authentication-plugin=mysql_native_password]
        ports
            - ${MYSQL_PORT}3306
        environment
            MYSQL_ROOT_PASSWORD ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE ${MYSQL_DATABASE}
            MYSQL_USER ${MYSQL_USER}
            MYSQL_PASSWORD ${MYSQL_PASSWORD}
        volumes
            - .dbvarlibmysql

    php
        container_name php-fpm
        build
            context .php-fpm
            args
                PHP_XDEBUG_MODE ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION 4.23.2
        ports
            - ${PHP_PORT}9001
        volumes
            - .symfonyvarwwwsymfonycached
            - .logssymfonyvarwwwsymfonyvarlogcached
        depends_on
            - db

    phpmyadmin
        image phpmyadmin
        container_name phpmyadmin
        environment
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports
            - ${PHPMYADMIN_PORT}80
        restart always

    nginx
        container_name nginx
        build 
            context .nginx
            args
                NGINX_SYMFONY_SERVER_NAME ${NGINX_SYMFONY_SERVER_NAME}
                KIBANA_PORT ${KIBANA_PORT}
        ports
            - ${NGINX_PORT}80
        depends_on
            - php
        environment
            - NGINX_ENVSUBST_OUTPUT_DIR=etcnginxconf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=etcnginxtemplates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
            - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
        volumes
            - .logsnginxvarlognginxcached
            - .symfonyvarwwwsymfonycached

    elasticsearch
        container_name elasticsearch
        image docker.elastic.coelasticsearchelasticsearch7.10.1
        environment
            discovery.type single-node
        ports
            - ${ELASTICSEARCH_PORT}9200

    logstash
        container_name logstash
        image docker.elastic.cologstashlogstash7.10.1
        depends_on
            - elasticsearch
        volumes
            - .elklogstashpipelines.ymlusrsharelogstashconfigpipelines.ymlcached
            - .elklogstashconf.detclogstashconf.dcached
            - .logssymfonyvarwwwsymfonyvarlogcached
            - .logsnginxvarlognginxcached

    kibana
        container_name kibana
        depends_on
            - elasticsearch
        image docker.elastic.cokibanakibana7.10.1
        environment
            SERVER_NAME localhost
            ELASTICSEARCH_HOSTS httpelasticsearch9200
        ports
            - ${KIBANA_PORT}5601
    networks:
      - laravel